theme: jekyll-theme-minimal
title: Pete's Website
description: A place for some things
show_downloads: false
github:
  is_project_page: false
  owner_name: false
# google_analytics: [Your Google Analytics tracking ID]